### ISSUE TITLE
Document how to migrate to the new Mbed tools

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbed-tools#227]
### Description

As an old-time Mbed user, I want to understand how to use the new Mbed tools

- Create a migration guide to help teach the new tools
- How to do what you used to do with the old tools, but with the new tools now

### Issue request type

- [X] Enhancement
- [ ] Bug

### Tasks

- [ ] Come up with lower-level commands where we've removed top level command
- [ ] Add rationale for command removal
- [ ] mbed-os-5-docs review

**Comment by Patater** [comment]
PR up at https://github.com/ARMmbed/mbed-os-5-docs/pull/1441
